# Generated by Django 4.1.5 on 2023-05-26 14:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone Number')),
                ('address', models.TextField(verbose_name='Address')),
                ('payment_due', models.IntegerField(verbose_name='Payment Due')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
