# Generated by Django 4.1.5 on 2023-05-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('NET', 'Net Banking')], default='CASH', max_length=10, verbose_name='Mode'),
        ),
    ]
